### PR TITLE
Aircon2

### PR DESCRIPTION
**Pull request by nora0706**
- Add support of aircon 2 accessary
- Update readme
- Fix bug that garagedoor and fan are shown as thermostat

### CODE REVIEW

**Comment by nora0706** [comment]
Created this PR mistakenly. Sorry and please ignore it.

**Comment by zladukas** [comment]
Since this rep is not being maintained, you can try to merge with AlexanderBabel/homebridge-broadlink-rm

**Comment by Faisalthe01** [comment]
Hi @nora0706. What does AirCon 2 does?

**Comment by nora0706** [comment]
> Hi @nora0706. What does AirCon 2 does?

Hi @Faisalthe01. The AirCon 2 is used for those air conditioners which have both cooling mode and heating mode. It provide the functionality to set the air conditioner to a specific mode with a specific temperature. But as @zladukas mentioned, there is a AlexanderBabel/homebridge-broadlink-rm which has this functionality already so please check it out.

**Pull request closed without merging**
