### PR TITLE
Rewrite readme

### PR DESCRIPTION
**Pull request by alexymik**
Rewrite and re-order readme.

Main changes:

- Remove instructions on installing homebridge. There are more complete directions on the project page.
- Add more detail on plugin setup and use.
- Add examples for each accessory type.
- Misc cleanup and reordering.

### CODE REVIEW

**Comment by felipesalomao** [comment]
Hi, do you know how to change status of device (on or off) by command line? I plan change status after receive some hex ir, so this way i could "sync" tv remote or other device with homekit.. Today if you power on tv, then turn off with tv remote, homekit still think that tv is on.. I would like to run external software/script that after receive hex command, it change status of device..  First step is to know how change status by command.. Thank you

**Comment by alexymik** [comment]
Hi,
This is a pull request for documentation and not the correct place for your question. Your question is also not specific to this plugin; homebridge is what dictates accessory states

Go to: https://github.com/nfarina/homebridge
Possible solution: https://github.com/nfarina/homebridge/issues/506

**Comment by felipesalomao** [comment]
Thank you. I know that i am on not correct place, its just i dont see any activies last months.. This pull request was accepted?

**Comment by alexymik** [comment]
Not yet, still open. I hope it will be reviewed soon

**Comment by felipesalomao** [comment]
I think that owner abandoned this.. Last commit was july.. Last open pull request also was july.. It have really good potential.. But to be perfect should add one really important feature, sync online commands (siri) with offline commands (tv remote, air conditioner remote, etc), this way would make devices really smart.. Today status of device is aways wrong (because you dont use just homekit).. But to do that, it would envolve broadlink device to.. (to aways listen IR and change device status).. Lets Hope this project developer or somebody forks it.. Anyway i will do research of how can i do something like it..

**Comment by alexymik** [comment]
Sorry but I am having trouble understanding what you mean. The Broadlink unit has no idea what the state of the device is (or even if the signal was received by the device). This is why the disableAutomaticOff parameters are there.

If you need this feedback then you should look at another solution that needs to physically or electrically interact with the target device.

**Comment by felipesalomao** [comment]
yes, i know that can use disableAutomaticOff .. but this is no real solution.

Imagine that situation:
Today work this way:

Turn on tv  using homekit (homebridge)

Status of homebridge tv device turn "on"

Then, you turn off using tv remote control (offline device)

Status of homebridge tv device continues "on" because it cant know that tv was truned off using tv remote control

------------------------------------------------ What i would like to change (depend new features)

Turn on tv  using homekit (homebridge)

Status of homebridge tv device turn "on"

Then, you turn off using tv remote control (offline device)

New  --> Broadlink  would aways listen infrared  command, then  if detect tv remote control power hex signal, it would change status of homebridge tv device to "off"

This way, aways status of devices would be right..

**Comment by tianshuo** [comment]
@alexymik Hi, could you change the required status of key-values, into a separate column? Like this:

| key | Description | value| default value| Required|
|--|--|--|--|--|
|`name` | A descriptor for the accessory that will show in HomeKit apps. | `"TV"` | -|Required|
 |`type` | The type of accessory. | `"switch"` | -|Required|
 |`persistState` | Determines whether the state of accessory persists after homebridge has been restarted. | `false` | `true` | Optional|
 |`resendHexAfterReload` | When persistState is true (it is by default) this will resend the hex code for the last known state if homebridge is restarted. | `true` | `false` | Optional|
 |`disableLogs` | Disables the log output for this accessory. | `true` | `false` |Optional|

**Comment by lprhodes** [comment]
Thanks for all of the work you did on this. I've taken on board a lot of the input but unfortunately there were too many changes that I didn't want to move over and too much movement of text for me to be able to use this PR.

**Pull request closed without merging**
