### PR TITLE
Add FanV2 to accessories

### PR DESCRIPTION
**Pull request by duyleekun**
I have fan in my home with swing and speed toggle button on the remote only. 
Hope this help :)

### CODE REVIEW

**Comment by lprhodes** [comment]
@duyleekun What does the Home app UI look like fan fans?

**Comment by duyleekun** [comment]
@lprhodes This one is unsupported by home app UI, but Siri can understand all commands. 

Turn on/off fan
Turn on/off fan swing
Increase/decrease/set fan speed

I'm trying to test with having 2 services in this new fan accessory. FanV1 and FanV2 (FanV1 does gets Home UI supported with only on/off)

**Comment by lprhodes** [comment]
OK - thanks. Does Siri max out at speed 10 or is it a %? Having a toggle for speed feels odd.

**Comment by duyleekun** [comment]
@lprhodes
```
Characteristic.RotationSpeed = function() {
  Characteristic.call(this, 'Rotation Speed', '00000029-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.FLOAT,
    unit: Characteristic.Units.PERCENTAGE,
    maxValue: 100,
    minValue: 0,
    minStep: 1,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.WRITE, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};
```

**Comment by lprhodes** [comment]
Ha, I didn't even think to look at that, I'm tired :) Thanks!

**Comment by lprhodes** [comment]
Weird that there's only a rotation speed and not a fan speed.

**Comment by duyleekun** [comment]
@lprhodes It does feel odd, moving to the AC type you invented would make it better.
But I'm thinking to DRY the whole thing. Following are quite common thing for characteristic :)
- get/set boolean
- get/set float

**Comment by duyleekun** [comment]
@lprhodes rotation speed is fan speed :) Not the swinging speed I suppose :)

**Comment by lprhodes** [comment]
@duyleekun ah got it. You don't have to actually say "rotation speed" right? You can say fan speed?

**Comment by duyleekun** [comment]
Yeah :) `Set fan speed to 15` does work :)

**Comment by lprhodes** [comment]
Great - I'll update to support fanSpeedX in the data and it will use the hex code that's closest to the speed you ask for

**Comment by duyleekun** [comment]
@lprhodes Yeah, extract the implementation from the AC to some helper file and reuse it here will make this awesome :)

**Comment by duyleekun** [comment]
@lprhodes I feel pretty bad when we have to repeat the whole boolean characteristic over and over again :)

**Comment by lprhodes** [comment]
@duyleekun AC is working a little different, I'll consider whether I move to "use the nearest hex" over "use the default hex" after for the AC.

>  I feel pretty bad when we have to repeat the whole boolean characteristic over and over again :)
How do you mean?

**Comment by duyleekun** [comment]
@lprhodes I meant this whole thing is quite repetitive

```
setSwitchState (onHex, offHex, currentStatus, callback) {
    const { host, log } = this

    log(`setSwitchState: ${currentStatus}`);

    const hexData = currentStatus ? onHex : offHex;
    this.switchState = currentStatus

    sendData(host, hexData, callback, log);
  }
getSwitchState (callback) {
    this.log(`getSwitchState: ${this.switchState}`);
    callback(null, this.switchState)
  }
```

We should have a helper method that generate those 2 functions (boolean, float with min max should be auto supported). After we have that generator, we can do this
```
this.handleCharacteristic(service, Characteristic.On,'switchState') //switchState is the name of the attribute that we save inside this.accesoryState['switchState']
```

**Comment by lprhodes** [comment]
Yeah I agree - I'm writing that as I just got your response :)

**Comment by duyleekun** [comment]
@lprhodes Yeah, I'm looking forward for it :) Although it's not really a feature :)

**Comment by duyleekun** [comment]
@lprhodes But after this, we can loop all Service in the `HAP-NodeJS` and handle all the Service automatically :) The only thing left is auto documentation :))

**Comment by lprhodes** [comment]
...though I'm adding an optional parameter to it.

Then we can have methods like this:

`super.createToggleCharacteristic(service, Characteristic.RotationSpeed, 'rotationSpeed', this.setRotationSpeed)`

```
  setRotationSpeed (currentStatus, callback) {
    const { data } = this
    const { swingToggle } = data

    sendData(host, swingToggle, callback, log);
  }
```

I'm not a fan of looping through the accessories that way - there's generally some customisation needed on each to make it a great implementation. I'd rather take them one at a time.

**Comment by lprhodes** [comment]
@duyleekun I've started the simplicatin here https://github.com/lprhodes/homebridge-broadlink-rm/tree/feature/simplify-toggle-characteristics - I've not tested it yet though

**Comment by duyleekun** [comment]
@lprhodes Yeah. But calling it createBooleanCharacteristic would be more generic. Your code supported all `Characteristic.Formats.BOOL` characteristics anyway. There's only a few characteristic format I think :)

**Pull request merged**
